### ISSUE TITLE
What is the best way for store long values?

### ISSUE THREAD

**Issue by AgoL5866** [torquem-ch/mdbx-go#101]
when I want to store the values which abount 100K ~ 1000K, on my  ssd disk the benchmark put function is less than 1000 per second.

this is my mdbx env.Open flag :

```
mdbx.Accede | mdbx.UtterlyNoSync | mdbx.Coalesce | mdbx.NoReadahead
```

key, val = 20 bytes:
```
BenchmarkMdbxStorage_Set-8   	 1152529	      1884 ns/op	     144 B/op	       6 allocs/op
```

key = 20bytes, val = 512K bytes
```
BenchmarkMdbxStorage_Set-8   	     720	   1521572 ns/op	     141 B/op	       6 allocs/op

```

So, when I store 1 large item, it will take more than 1ms, what is the best way to use mdbx store 100K ~ 1000K item?

**Comment by AskAlexSharov** [comment]
@AgoL5866 
1. increase db page_size to 64kb (you will have less overflow pages and less FreeList overhead)
2. increase mdbx_env_set_geometry growStep and initialSize
3. check that you do zero-copy. also please try: `put(MDBX_RESERVE)` 
4. add WriteMap flag. With this flag - latest version of mdbx, can create-new-pages and fully-re-write-existing-pages without triggering page-fault. may greatly help for "copy database" or "large values insert" use-cases.
