### ISSUE TITLE
Great work! appreciate if can emphasize this section....

### ISSUE THREAD

**Issue by hiqsociety** [torquem-ch/mdbx-go#11]
1. what's the cost of runtime safety?
2. how much faster? 2x? 3x? ( just wondering if worth while to implement over safety issues)

Zero-copy reads
Applications with high performance requirements can opt-in to fast, zero-copy reads at the cost of runtime safety. Zero-copy behavior is specified at the transaction level to reduce instrumentation overhead.

**Comment by AskAlexSharov** [comment]
- It allows to refer db memory regions, without copy bytes. But memory regions of db are valid only during transaction. Means you can't read same []byte after tx finish (can but it may have invalid data, or not exist at all).
- It's safe if you don't use WriteMap, just can't use anything what db returns outside of Tx without copying.
- If you use WriteMap - then you should not write to memory regions returned by DB - to modify data in db need use only Put/Delete methods. But if you will write - nobody will stop you (OS will kill app if you try to write in DB memory region without WriteMap flag).
