### ISSUE TITLE
mdbx-go crashes under windows

### ISSUE THREAD

**Issue by jackliu10** [torquem-ch/mdbx-go#31]
System information 

which the exact version of Windows you're on ?
I have tried multiple versions of windows and it will reproduce，This crash has been in the version starting in July
Windows 11 21H2 22000.120 1000.22000.120.0

May I ask which version of GO are you on ?
go version go1.16.7 windows/amd64

how much free disk space you have on C: ?
My free disk space have on C: is 1.9T (PM9A1 2T PCIE4.0 NVME m.2)

how much RAM on your system ?
64.0 GB

are you running on a virtualized machine or physical ?
Physical machine

 Expected behaviour
run

 Actual behaviour
panic

 Steps to reproduce the behaviour
just run erigon.exe at windows

 Backtrace
![image](https://user-images.githubusercontent.com/40690755/129020435-0f144e8c-1fb0-4177-a0ba-337efc47ee46.png)
Microsoft Windows [版本 10.0.22000.120]
(c) Microsoft Corporation。保留所有权利。

c:\weup\src\github.com\ledgerwatch\mdbx-go\mdbx>go test
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime: unknown pc 0x356f55
stack: frame={sp:0xb21f1ffc80, fp:0x0} stack=[0x0,0xb21f1ffda0)
000000b21f1ffb80:  0000000000000330  0000000000000000
000000b21f1ffb90:  0000000b00000040  0000000ffa66b000
000000b21f1ffba0:  0000000e1220a000  000000125a66b000
000000b21f1ffbb0:  0000000fcf78a000  00007ffffffe0000
000000b21f1ffbc0:  00007ffed3c6f000  0000000000000000
000000b21f1ffbd0:  0000000002030000  0000000000000000
000000b21f1ffbe0:  0000000000000000  00000007fffffff0
000000b21f1ffbf0:  00007ffd827c8e50  000000c0000ac510
000000b21f1ffc00:  0000026cd04e9510  00007ffd827c8ee9
000000b21f1ffc10:  000000c000089de0  00000000b4bbbdff
000000b21f1ffc20:  0002625a00000000  00ffa66b00001000
000000b21f1ffc30:  0102f2ff00000001  0000000000010000
000000b21f1ffc40:  0000000000ffa66b  0000000000e1220a
000000b21f1ffc50:  00000000ffffffff  0000026cd04e93d0
000000b21f1ffc60:  0000b79ce51fd316  000000c0000ac510
000000b21f1ffc70:  000000c0000ac510  0000000000356f55
000000b21f1ffc80: <00000000001f776f <runtime.semawakeup+47>  0000026cd04e93d0
000000b21f1ffc90:  0000000000000000  0000000000000000
000000b21f1ffca0:  00000000004a01c8  0000000000379b80
000000b21f1ffcb0:  0000100000000009  0000000000010000
000000b21f1ffcc0:  00007ffffffeffff  00000000ffffffff
000000b21f1ffcd0:  000021d800000020  2100001900010000
000000b21f1ffce0:  000000c000089e20  00000000004d65c0
000000b21f1ffcf0:  000000c00008a000  0000000000314aea
000000b21f1ffd00:  000000000022a88a <runtime.callers.func1+138>  00000000002ad51f <testing.callerName+95>
000000b21f1ffd10:  000000c000089f40  0000000000000000
000000b21f1ffd20:  000000c000089e20  00000000004d65c0
000000b21f1ffd30:  000000c000089e20  0000000000230e93 <runtime.asmcgocall+115>
000000b21f1ffd40:  0000000000000000  0000000000000000
000000b21f1ffd50:  0000000000000000  0000000000000001
000000b21f1ffd60:  000000c000089ee0  0000000000000250
000000b21f1ffd70:  000000c000075380  0000000000201440 <runtime.mstart+0>
runtime: unknown pc 0x356f55
stack: frame={sp:0xb21f1ffc80, fp:0x0} stack=[0x0,0xb21f1ffda0)
000000b21f1ffb80:  0000000000000330  0000000000000000
000000b21f1ffb90:  0000000b00000040  0000000ffa66b000
000000b21f1ffba0:  0000000e1220a000  000000125a66b000
000000b21f1ffbb0:  0000000fcf78a000  00007ffffffe0000
000000b21f1ffbc0:  00007ffed3c6f000  0000000000000000
000000b21f1ffbd0:  0000000002030000  0000000000000000
000000b21f1ffbe0:  0000000000000000  00000007fffffff0
000000b21f1ffbf0:  00007ffd827c8e50  000000c0000ac510
000000b21f1ffc00:  0000026cd04e9510  00007ffd827c8ee9
000000b21f1ffc10:  000000c000089de0  00000000b4bbbdff
000000b21f1ffc20:  0002625a00000000  00ffa66b00001000
000000b21f1ffc30:  0102f2ff00000001  0000000000010000
000000b21f1ffc40:  0000000000ffa66b  0000000000e1220a
000000b21f1ffc50:  00000000ffffffff  0000026cd04e93d0
000000b21f1ffc60:  0000b79ce51fd316  000000c0000ac510
000000b21f1ffc70:  000000c0000ac510  0000000000356f55
000000b21f1ffc80: <00000000001f776f <runtime.semawakeup+47>  0000026cd04e93d0
000000b21f1ffc90:  0000000000000000  0000000000000000
000000b21f1ffca0:  00000000004a01c8  0000000000379b80
000000b21f1ffcb0:  0000100000000009  0000000000010000
000000b21f1ffcc0:  00007ffffffeffff  00000000ffffffff
000000b21f1ffcd0:  000021d800000020  2100001900010000
000000b21f1ffce0:  000000c000089e20  00000000004d65c0
000000b21f1ffcf0:  000000c00008a000  0000000000314aea
000000b21f1ffd00:  000000000022a88a <runtime.callers.func1+138>  00000000002ad51f <testing.callerName+95>
000000b21f1ffd10:  000000c000089f40  0000000000000000
000000b21f1ffd20:  000000c000089e20  00000000004d65c0
000000b21f1ffd30:  000000c000089e20  0000000000230e93 <runtime.asmcgocall+115>
000000b21f1ffd40:  0000000000000000  0000000000000000
000000b21f1ffd50:  0000000000000000  0000000000000001
000000b21f1ffd60:  000000c000089ee0  0000000000000250
000000b21f1ffd70:  000000c000075380  0000000000201440 <runtime.mstart+0>

goroutine 6 [syscall]:
github.com/torquem-ch/mdbx-go/mdbx._Cfunc_mdbx_env_create(0xc0000ac510, 0xc000000000)
        _cgo_gotypes.go:620 +0x4b
github.com/torquem-ch/mdbx-go/mdbx.NewEnv.func1(0xc0000ac510, 0xc0000ac510)
        c:/weup/src/github.com/ledgerwatch/mdbx-go/mdbx/env.go:137 +0x66
github.com/torquem-ch/mdbx-go/mdbx.NewEnv(0x2ad766, 0x4b1970, 0x41f37d)
        c:/weup/src/github.com/ledgerwatch/mdbx-go/mdbx/env.go:137 +0x4b
github.com/torquem-ch/mdbx-go/mdbx.setupFlags(0x40ba30, 0xc000075200, 0x0, 0x379b80)
        c:/weup/src/github.com/ledgerwatch/mdbx-go/mdbx/env_test.go:496 +0x2d
github.com/torquem-ch/mdbx-go/mdbx.setup(...)
        c:/weup/src/github.com/ledgerwatch/mdbx-go/mdbx/env_test.go:492
github.com/torquem-ch/mdbx-go/mdbx.TestCursor_Txn(0xc000075200)
        c:/weup/src/github.com/ledgerwatch/mdbx-go/mdbx/cursor_test.go:15 +0x4b
testing.tRunner(0xc000075200, 0x3dec60)
        C:/Program Files/Go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1238 +0x2b3

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000075200, 0x3d4375, 0xe, 0x3dec60, 0x251bed)
        C:/Program Files/Go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000075080)
        C:/Program Files/Go/src/testing/testing.go:1511 +0x7f
testing.tRunner(0xc000075080, 0xc0000bdde0)
        C:/Program Files/Go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc000004078, 0x38d460, 0x3d, 0x3d, 0xc03d0ad69a213fa8, 0x8bb3012681, 0x4d6300, 0x3d4109)
        C:/Program Files/Go/src/testing/testing.go:1509 +0x310
testing.(*M).Run(0xc0000dc000, 0x0)
        C:/Program Files/Go/src/testing/testing.go:1417 +0x1f5
main.main()
        _testmain.go:187 +0x145
rax     0x0
rbx     0x26cd04e93d0
rcx     0x26cd04e9558
rdi     0xc0000ac510
rsi     0x7ffd827c8e50
rbp     0xc000089de0
rsp     0xb21f1ffc78
r8      0x2d
r9      0x3e
r10     0x0
r11     0x3ef6e5f10e4be44
r12     0x404ed0
r13     0x0
r14     0x0
r15     0x2030000
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
exit status 2
FAIL    github.com/torquem-ch/mdbx-go/mdbx      0.523s

c:\weup\src\github.com\ledgerwatch\mdbx-go\mdbx>

**Comment by AndreaLanfranchi** [comment]
Closed by https://github.com/ledgerwatch/erigon/issues/2507#issuecomment-897906570
