### ISSUE TITLE
more examples of the api would be great, error in a simple demo

### ISSUE THREAD

**Issue by guanqun** [torquem-ch/mdbx-go#60]
```
package main

import (
	"fmt"
	"github.com/torquem-ch/mdbx-go/mdbx"
	"os"
)

func main() {
	env, err := mdbx.NewEnv()
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to create mdbx env: %s\n", err)
		os.Exit(1)
	}

	env.SetOption(mdbx.OptMaxDB, 20)

	err = env.Open("/tmp/test-mdbx", mdbx.Coalesce|mdbx.LifoReclaim|mdbx.WriteMap, 0664)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to open the env: %s\n", err)
		os.Exit(1)
	}

	idx := 0

	updateDbFunc := func(txn *mdbx.Txn) error {
		dbi, err := txn.CreateDBI("hello")
		if err != nil {
			fmt.Fprintf(os.Stderr, "failed to create dbi: %s\n", err)
			os.Exit(1)
		}

		for i := 0; i < 1024*1024*2; i++ {
			key := fmt.Sprintf("abcdef%d", idx)
			idx += 1

			err = txn.Put(dbi, []byte(key), []byte("xyzxyz"), 0)
			if err != nil {
				// some errors
				fmt.Fprintf(os.Stderr, "failed to write to db: %s\n", err)
				os.Exit(1)
			}
		}

		env.CloseDBI(dbi)

		return nil
	}
	env.Update(updateDbFunc)

	env.Close()
}
```

In this simple demo, I got errors: 

```
failed to write to db: mdbx_put: MDBX_MAP_FULL: Environment mapsize limit reached
```

Would someone help illuminate which parat I'm missing?

**Comment by guanqun** [comment]
shouldn't mdbx handle the mmap by itself?

**Comment by AndreaLanfranchi** [comment]
You need to specify a value for mapsize (which MDBX defaults to 1MiB) This value defines the **maximum size of file on disk**.
In your example you're writing `1024*1024*2*6` bytes of data only. To that value you must add page splitting (each MDBX data page is 4KiB) and btree structure. Thus you overflow the default MAX size.
See [here](https://github.com/ledgerwatch/erigon-lib/blob/main/kv/mdbx/kv_mdbx.go#L154-L310) 

I reiterate ... mapsize sets the MAX size of data file on disk. It does not mean all space is immediately allocated.

**Comment by guanqun** [comment]
> You need to specify a value for mapsize (which MDBX defaults to 1MiB) This value defines the **maximum size of file on disk**. In your example you're writing `1024*1024*2*6*6` bytes of data only. To that value you must add page splitting (each MDBX data page is 4KiB) and btree structure. Thus you overflow the default MAX size. See [here](https://github.com/ledgerwatch/erigon-lib/blob/main/kv/mdbx/kv_mdbx.go#L154-L310)

Thank you for the great help, this seems a very important parameter, but it's buried in a weird API called "set_geometry()"...

> I reiterate ... mapsize sets the MAX size of data file on disk. It does not mean all space is immediately allocated.

I see it has a growth parameter.
