### ISSUE TITLE
Sequence returns value prior to increment?

### ISSUE THREAD

**Issue by missinglink** [torquem-ch/mdbx-go#63]
Hi,

Apologies if I'm reading this wrong, it seems to me that the `Sequence()` return value is equal to the `md_seq` *before* the increment and not after?

Shouldn't we be reading the value of `new`?

```
func (txn *Txn) Sequence(dbi DBI, increment uint64) (uint64, error) {
	var res C.uint64_t
	ret := C.mdbx_dbi_sequence(txn._txn, C.MDBX_dbi(dbi), &res, C.uint64_t(increment))
	if ret != 0 {
		return uint64(res), operrno("mdbx_dbi_sequence", ret)
	}
	return uint64(res), nil
}
```

<img width="553" alt="Screenshot 2022-04-29 at 10 42 53" src="https://user-images.githubusercontent.com/738069/165912314-5340cff7-0e00-4e82-9da9-c25d88b51399.png">

**Comment by AskAlexSharov** [comment]
This repo is just a wrapper for C code. Better as this question at https://gitflic.ru/project/erthink/libmdbx/
I personally don't see difference.

**Comment by missinglink** [comment]
It's just that, to me, the function isn't very intuitive:

```go
fmt.Println(txn.Sequence(dbi, 0))       // 0 <nil>
fmt.Println(txn.Sequence(dbi, 1))       // 0 <nil>
fmt.Println(txn.Sequence(dbi, 4))       // 1 <nil>
fmt.Println(txn.Sequence(dbi, 0))       // 5 <nil>
```

In order to retrieve the current sequence value, the user must first check for an error and if it's null then add the `$increment` value to the returned `uint64` otherwise the value returned is equal to the state *before* the change.

It seems like that behaviour should be hidden from the user?

**Comment by missinglink** [comment]
It's uncomfortable software ergonomics, which I can see biting almost every user at some point.

**Comment by AskAlexSharov** [comment]
"user must first check for an error" - it's always in golang
"add the $increment value to the returned" - i don't see why need to add something. in my head pattern looks as:
``` 
baseId, err := txn.Sequence(dbi, N)
if err != nil {
   return err
}
for i := 0; i < N; i++ {    // if N == 0, it will work as expected
    id := baseId + i
    // use id  
}
```
or if need only 1 id in code: 
```
id, err := txn.Sequence(dbi, 1)
if err != nil {
    return err 
}
// use id
```

**Comment by missinglink** [comment]
what do you expect the value of `id` to be?

```go
id, err := txn.Sequence(dbi, 1)
if err != nil {
    return err 
}
// use id
```

**Comment by AskAlexSharov** [comment]
Value which I can use as-is - as auto-increment id of some entity.
