### ISSUE TITLE
mdbx_env_open: MDBX_BUSY

### ISSUE THREAD

**Issue by missinglink** [torquem-ch/mdbx-go#71]
opening the same path twice results in an `MDBX_BUSY` error despite not passing the `MDBX_EXCLUSIVE` flag 🤷‍♂️ 

```
panic: mdbx_env_open: MDBX_BUSY: Another write transaction is running, 
or environment is already used while opening with MDBX_EXCLUSIVE flag
```

in the example below there is neither a write transaction running, nor were either opened with the `MDBX_EXCLUSIVE` flag: 

```go
package main

import (
	"fmt"
	"io/ioutil"

	"github.com/torquem-ch/mdbx-go/mdbx"
)

func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	// create a temporary directory
	tmpdir, err := ioutil.TempDir("", "mdbx")
	check(err)
	datpath := fmt.Sprintf("%s/foobar.db", tmpdir)
	fmt.Println("datpath:", datpath)

	// open environment
	env1, err := mdbx.NewEnv()
	check(err)
	check(env1.Open(datpath, mdbx.NoSubdir, 444))
	flag1, err := env1.Flags()
	check(err)
	fmt.Println("exclusive:", flag1&mdbx.Exclusive)

	// open new environment
	env2, err := mdbx.NewEnv()
	check(err)
	check(env2.Open(datpath, mdbx.NoSubdir, 444))
}
```

```
cat go.sum
github.com/torquem-ch/mdbx-go v0.23.2 h1:7axXl0leix2v8No+mRzeTV32hJrV1817aKhh+hTEpC8=
github.com/torquem-ch/mdbx-go v0.23.2/go.mod h1:T2fsoJDVppxfAPTLd1svUgH1kpPmeXdPESmroSHcL1E=
```

**Comment by missinglink** [comment]
note: changing the file permissions from `444` to `777` results in a different error, equally puzzling:

```
panic: mdbx_env_open: MDBX_PANIC: Likely because hardware failure. Before creating issue please use tools like 
https://www.memtest86.com to test RAM and tools like https://www.smartmontools.org to test Disk. 
To handle hardware risks: use ECC RAM, use RAID of disks, run multiple application instances (or do backups). 
If hardware checks passed - check FS settings - 'fsync' and 'flock' must be enabled.  
Otherwise - please create issue in Application repo. On default DURABLE mode, power outage can't cause this error. 
On other modes - power outage may break last transaction and mdbx_chk can recover db in this case, see '-t' and '-0|1|2' options.
```

**Comment by missinglink** [comment]
agh so, after reading through `mdbx.h` I found this:

```
 * \retval MDBX_BUSY          The \ref MDBX_EXCLUSIVE flag was specified and the
 *                            environment is in use by another process,
 *                            or the current process tries to open environment
 *                            more than once.
 ```
 
 The last two lines explain this issue `or the current process tries to open environment more than once`.

**Comment by missinglink** [comment]
It seems the issue with the error message not being descriptive enough is in the C lib, so I'm going to close here as there's not much this library can do about it.

```
"MDBX_BUSY: Another write transaction is running,"
      " or environment is already used while opening with MDBX_EXCLUSIVE flag",
```

**Comment by AndreaLanfranchi** [comment]
You definitely can open the same env path twice as long as the second instance opening the file uses the `MDBX_ACCEDE` in the env opening flags

**Comment by missinglink** [comment]
Thanks @AndreaLanfranchi, unfortunately this is not the case when the same env is opened by the same process, even when done inside a new goroutine.

**Comment by AndreaLanfranchi** [comment]
I'm not sure why you would open the same env twice in the same process : you can pass around the env reference among threads. The important thing is that you can't have more than 1 RW transaction at a time and that each transaction lives (and dies) in the thread it was originally created.

**Comment by missinglink** [comment]
I'm benchmarking poor parallel read performance and was experimenting with this as a potential solution.

The benchmarks are showing that spawning many goroutines, each opening a new RO transactions as such `env.BeginTxn(nil, mdbx.Readonly)` will block the routine, these blocks are preventing parallel reads of the memory map and I'm not sure why 🤔

**Comment by missinglink** [comment]
This library strictly enforced `MDBX_NOTLS ` and is not configurable to run without it enabled:
https://github.com/torquem-ch/mdbx-go/blob/master/mdbx/env.go#L147
