### ISSUE TITLE
Can we get db snapshot like goleveldb?

### ISSUE THREAD

**Issue by hadv** [torquem-ch/mdbx-go#74]
Can we get db snapshot like goleveldb?

https://github.com/syndtr/goleveldb/blob/master/leveldb/db.go#L918

**Comment by hadv** [comment]
And like pebble as well?

https://github.com/cockroachdb/pebble/blob/master/db.go#L1146

**Comment by AskAlexSharov** [comment]
yes, just open read transaction (db.View or db.BeginTxn)
